### ISSUE TITLE
sidecar does not work for helm templates

### ISSUE THREAD

**Issue by MarcMielke** [IBM/kui#1808]
can not read a block mapping entry; a multiline key may not be an implicit key at line 7, column 12:
        release: {{ .Release.Name }}

or

missed comma between flow collection entries at line 1, column 3:
    {{- if .Values.dashboardImport.ena ...

**Comment by starpit** [comment]
thanks for the bug report! would you be able to provide an example input?

**Comment by ydarias** [comment]
I reproduced the error.

**Comment by ydarias** [comment]
I reproduced the error.

1. Navigate to a folder with a set of Helm templates.
2. Click on one template to be opened in the sidecar.

In my case, it failed with the file below.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: us.icr.io/kui-shell/kui-landing:{{ .Values.image.version }}
        imagePullPolicy: Always
      imagePullSecrets:
      - name: {{ .Values.image.secret }}
```

with error

```
can not read a block mapping entry; a multiline key may not be an implicit key at line 5, column 9:
      labels:
            ^
```
