### ISSUE TITLE
we should put all the related cert files specified in kubeconfig in proxy docker

### ISSUE THREAD

**Issue by myan9** [IBM/kui#1818]
Currently, we only copy ~/.kube/ into proxy docker, which doesn't work for those clusters putting cert files outside of ~/.kube/, e.g. minikube puts its own cert files in ~/.minikube/

To solve this issue, we should look for the file paths specified in kubeconfig and copy them into proxy docker for the users. Take minikube as an example, the kubeconfig of users.minikube looks like the following :
```
- name: minikube
  user:
    client-certificate: /Users/mengting.yan1ibm.com/.minikube/client.crt
    client-key: /Users/mengting.yan1ibm.com/.minikube/client.key
```
