### ISSUE TITLE
weird formatting with cat yml file

### ISSUE THREAD

**Issue by rabbah** [IBM/kui#2408]
**Describe the bug**
YML file formatted oddly when cat'ed.

**Steps to reproduce the behavior**

1. Create `t.yml` with the following content
```yml
some:
  - name: default
    more:
      - name: config
        other:
```
2. `cat t.yml`

**Expected behavior**
Expecting normal formatting of a text file.

**Screenshots**
<img width="294" alt="Screen Shot 2019-08-17 at 2 18 27 PM" src="https://user-images.githubusercontent.com/4959922/63215804-e7365c80-c0f9-11e9-96c1-cf2d02dc9a11.png">
