### ISSUE TITLE
Carbon Gray10 - Contrast issue in sidecar tables

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#3540]
<img width="415" alt="Screen Shot 2020-01-24 at 10 21 10 AM" src="https://user-images.githubusercontent.com/26075187/73080212-77d84c00-3e93-11ea-80eb-6b8497958475.png">
<img width="285" alt="Screen Shot 2020-01-24 at 10 21 31 AM" src="https://user-images.githubusercontent.com/26075187/73080214-77d84c00-3e93-11ea-95f4-ce1f74fe2f1a.png">

**Comment by starpit** [comment]
this is what i see with carbon-themes 5.7.50:

<img width="672" alt="Screen Shot 2020-01-24 at 8 24 21 PM" src="https://user-images.githubusercontent.com/4741620/73114341-a253f480-3ee7-11ea-8ba2-65b0c0fe51ac.png">

**Comment by showeimer** [comment]
@starpit Not sure about the discrepancy but I see the lines of code in question in the master branch:

https://github.com/IBM/kui/blob/master/plugins/plugin-carbon-themes/web/css/carbon-gray10.css#L88

```css
body[kui-theme="Carbon Gray10"] sidecar .bx--data-table td,
body[kui-theme="Carbon Gray10"] sidecar .bx--data-table th {
  color: var(--color-text-inverted03);
}
```

https://github.com/IBM/kui/blob/master/plugins/plugin-carbon-themes/web/css/carbon-gray10.css#L173

```css
body[kui-theme="Carbon Gray10"] .bx--data-table td {
  background-color: var(--color-base00);
}
```

<img width="259" alt="Screen Shot 2020-01-27 at 9 43 08 AM" src="https://user-images.githubusercontent.com/26075187/73183913-96d01b80-40e9-11ea-9c7b-c7af2171a50c.png">
