### ISSUE TITLE
some carbon icons render as a solid color

### ISSUE THREAD

**Issue by starpit** [IBM/kui#5829]
e.g. the `<i>` icon. this regression was triggered by updating to the latest carbon icons, and is caused by a css rule of ours that we need to refine. suggestion is to add this rule to the carbon themes:

```css
.sidecar-bottom-stripe-toolbar .sidecar-toolbar-text svg path.inner-path {
    fill: var(--color-text-01);
}
```
