### ISSUE TITLE
PatternFly LeftNav view has excessive padding

### ISSUE THREAD

**Issue by starpit** [IBM/kui#6038]
For some reason, we are adding a padding-top, on top of whatever padding the patternfly css uses:

```css
[kui-theme-style] .pf-c-nav .pf-c-nav__list {
    padding-top: 1em;
}
```
