### ISSUE TITLE
tab completion does not render well in minisplits

### ISSUE THREAD

**Issue by starpit** [IBM/kui#6752]
i think the completion list is rendered to the right of the prompt, rather than below it?
<img width="498" alt="Screen Shot 2021-01-26 at 3 08 53 PM" src="https://user-images.githubusercontent.com/4741620/105899255-6e267e80-5fe8-11eb-944b-1278c6946827.png">

**Comment by starpit** [comment]
ah, this is due to this css rule:
```css
.kui--scrollback[data-is-minisplit] .repl-input {
    flex-wrap: nowrap;
}
```

which was trying to help with long input lines greedily taking vertical space away from the Output
