### ISSUE TITLE
sidecar top tabs may not have the proper sidecar header color

### ISSUE THREAD

**Issue by starpit** [IBM/kui#6841]
This is a regression from the port of the sidecar tabs, from Carbon to PatternFly. We are missing a CSS rule for `.kui--sidecar-header`

```css
.kui--sidecar-tabs {
    background-color: var(--color-sidecar-header);
}
```
